#!/usr/bin/env bash
# PCPM afterRun hook — auto-generated by global-brain hook-engine
# Extracts knowledge from the completed session transcript and
# writes it back into the persistent brain stores.
# ALSO runs sin-brain auto-sync to keep global and local brain in sync.

BRAIN_CLI="/Users/jeremy/dev/Infra-SIN-Dev-Setup/src/cli.js"
BRAIN_ROOT="/Users/jeremy/dev/Infra-SIN-Dev-Setup"
PROJECT_ID="Infra-SIN-Dev-Setup"
SESSION_ID="session-$(date +%s)"

# Extract knowledge from the session transcript (runs LLM extraction)
node "$BRAIN_CLI" extract-knowledge \
  --root "$BRAIN_ROOT" \
  --project "$PROJECT_ID" \
  --session "$SESSION_ID" \
  2>/dev/null

# Sync project brain bidirectionally
if [ -n "$PROJECT_ROOT" ]; then
  node "$BRAIN_CLI" sync \
    --root "$BRAIN_ROOT" \
    --project "$PROJECT_ID" \
    --project-root "$PROJECT_ROOT" \
    2>/dev/null
fi

# SIN-BRAIN: Auto-sync after every chat turn — no manual intervention needed
node "$BRAIN_CLI" sync-chat-turn 2>/dev/null

# SIN-BRAIN: Check if new rules were discovered and add them to global brain
echo "[SIN-BRAIN] Auto-sync complete after chat turn."

echo "PCPM_AFTERRUN_COMPLETE=true"
