#!/usr/bin/env bash
# PCPM beforeRun hook — auto-generated by global-brain hook-engine
# Loads active context from the persistent brain and injects it
# into the current OpenCode session as a system-level preamble.

BRAIN_CLI="/Users/jeremy/dev/Infra-SIN-Dev-Setup/src/cli.js"
BRAIN_ROOT="/Users/jeremy/dev/Infra-SIN-Dev-Setup"
PROJECT_ID="Infra-SIN-Dev-Setup"
GOAL_ID="default-goal"
GOAL_DESC="Continue development"

# Generate active context JSON and write to temp file
CONTEXT_FILE="/tmp/pcpm-context-${PROJECT_ID}.json"

node "$BRAIN_CLI" context \
  --root "$BRAIN_ROOT" \
  --project "$PROJECT_ID" \
  --goal-id "$GOAL_ID" \
  --description "$GOAL_DESC" \
  > "$CONTEXT_FILE" 2>/dev/null

# If context generation succeeded, output it as system context
if [ -f "$CONTEXT_FILE" ] && [ -s "$CONTEXT_FILE" ]; then
  echo "PCPM_CONTEXT_LOADED=true"
  cat "$CONTEXT_FILE"
fi
